server:
  port: 8080

spring:
  application:
    name: bookrentalshop
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/bookrentalshop?allowPublicKeyRetrieval=true&characterEncoding=utf8&useSSL=false
    username: root
    password: test
    hikari:
      minimum-idle: 30
      maximum-pool-size: 30
      connection-timeout: 10000
      validation-timeout: 5000
      leak-detection-threshold: 60000
      auto-commit: true
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 1.0.0

logging:
  level:
    root: info

app:
  jwt:
    signing-key: aW8uanNvbndlYnRva2VuLnNlY3VyaXR5
    access-token-expiry: 10m
    refresh-token-expiry: 1h
